name: misfortune_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  bloc_concurrency: ^0.2.1
  cupertino_icons: ^1.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_web_plugins:
    sdk: flutter
  http: ^1.0.0
  js: ^0.6.0
  mobile_scanner: 5.1.0
  provider: ^6.0.0
  web_browser_detect: ^2.0.0

dev_dependencies:
  build_runner: ^2.0.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
